#!/usr/bin/env node
// Regenerates references/styles-index.md from the repo's manifest.json.
// Run after adding/removing styles:
//   node .claude/skills/retro-design/scripts/build-index.mjs
//
// This script is portable — it resolves the repo root relative to its own
// location, so the repo can be cloned anywhere.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Script lives at <repo>/.claude/skills/retro-design/scripts/build-index.mjs
// SKILL_DIR  = .claude/skills/retro-design
// REPO_ROOT  = three levels above SKILL_DIR
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const SKILL_DIR = join(SCRIPT_DIR, "..");
const REPO_ROOT = join(SKILL_DIR, "..", "..", "..");
const MANIFEST = join(REPO_ROOT, "manifest.json");
const OUT = join(SKILL_DIR, "references", "styles-index.md");

const PALETTE_COLS = 3; // first N palette colors shown per row

const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
const systems = manifest.systems.slice().sort((a, b) => a.id - b.id);

const header =
  `<!-- Auto-generated by scripts/build-index.mjs. Do not edit by hand.\n` +
  `   Source: manifest.json (repo root)\n` +
  `   Regenerate: node .claude/skills/retro-design/scripts/build-index.mjs -->\n\n` +
  `# Retro design catalog (${systems.length} systems)\n\n` +
  `Compact reference for style selection. For full tokens/component markup, read \`styles/<slug>/index.html\` from the repo root.\n\n`;

const tableHeader =
  `| Slug | Name | Era | Year | Top ${PALETTE_COLS} colors | Tags |\n` +
  `| --- | --- | --- | --- | --- | --- |\n`;

const rows = systems.map((s) => {
  const palette = (s.palette || [])
    .slice(0, PALETTE_COLS)
    .map((c) => `\`${c}\``)
    .join(" ");
  const tags = (s.tags || []).slice(0, 4).join(", ");
  const year = s.year ?? "—";
  return `| \`${s.slug}\` | ${s.name} | ${s.era || "—"} | ${year} | ${palette} | ${tags} |`;
});

const body = header + tableHeader + rows.join("\n") + "\n";
writeFileSync(OUT, body);
console.log(`wrote ${OUT}: ${systems.length} rows`);
